spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=PetCommunity;encrypt=false
spring.datasource.username=sa
spring.datasource.password=giahuymanh912005

spring.jpa.hibernate.ddl-auto=update

spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.SQLServerDialect


#jwt
jwt.secret_key =Ba8YBnrXqCJ2TeB8nJtvR11g1WvJAAHCrq9ouN11eLw= 
jwt.expired_time = 84600000

#Clodinary Config
cloudinary.cloud-name=dfsnuhsff
cloudinary.api-key=379372267231741
cloudinary.api-secret=eFpW61v4HBXlK8Ru55-TABkhlUA


# Cấu hình giới hạn dung lượng file upload (Ví dụ: Max 5MB)
spring.servlet.multipart.max-file-size=5MB
spring.servlet.multipart.max-request-size=5MB


